/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.ids.c3;

import it.unicam.cs.ids.c3.model.Clienti.Cliente;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
